---
- hosts: x
  become: true
  tasks:
    - name: Log error and pause workflow
      debug:
        msg: "Failed to configure SELinux: {{ error_msg }}"

    - name: Set fact for failure
      set_fact:
        selinux_failure: true
